version: "3.12"

services:
  chatbot_service:
    build: .
    container_name: chatbot_container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot_container.rule=Host(`chat.orleu.edu.kz`)"
      - "traefik.http.routers.chatbot_container.entrypoints=websecure"
      - "traefik.http.routers.chatbot_container.tls.certresolver=myresolver"
      - "traefik.http.services.chatbot_container.loadbalancer.server.port=8000"
    networks:
      - traefik_traefik-net
    env_file:
      - .env
    volumes:
      - ./chatbot:/app/chatbot
      - ./rag_pipeline:/app/rag_pipeline
      - ./data:/app/data
      - ./embed/page_examp.html:/app/embed/index.html
    command: >
      uvicorn chatbot.app:app --host 0.0.0.0 --port 8000 --reload
    
networks:
  traefik_traefik-net:
    external: true